#!/usr/bin/env bash
# PreToolUse guard for Edit/Write/NotebookEdit.
#
# Enforces two CLAUDE.md rules that are stated as absolute, not advisory:
#   - "Never edit packages/*/tests/*.spec.ts" (the specs are the contract)
#   - "solutions/*/tests/ is generated by scripts/sync-tests.sh — never hand-edit"
#
# Reads the tool call JSON on stdin, checks tool_input.file_path, and exits 2
# (blocking the call, with this script's stderr fed back to the model) when
# the path matches either forbidden pattern. Exits 0 otherwise.
set -euo pipefail

input="$(cat)"
file_path="$(printf '%s' "$input" | python3 -c '
import json, sys
try:
    data = json.load(sys.stdin)
except Exception:
    sys.exit(0)
print(data.get("tool_input", {}).get("file_path", ""))
')"

[ -n "$file_path" ] || exit 0

if [[ "$file_path" =~ /packages/[^/]+/tests/.*\.spec\.ts$ ]] && [ -e "$file_path" ]; then
  echo "Blocked: $file_path is an existing exercise spec file." >&2
  echo "CLAUDE.md rule: 'Never edit packages/*/tests/*.spec.ts — the tests are the spec.'" >&2
  echo "Make the test pass by implementing in the exercise's src/ instead." >&2
  echo "(Creating a brand-new spec file for a new exercise is unaffected by this guard.)" >&2
  exit 2
fi

if [[ "$file_path" =~ /solutions/[^/]+/tests/ ]]; then
  echo "Blocked: $file_path is a generated solution test copy." >&2
  echo "CLAUDE.md rule: 'solutions/*/tests/ is generated by scripts/sync-tests.sh — never hand-edit a solution test copy.'" >&2
  echo "Edit the corresponding file under packages/<exercise>/tests/ and run 'pnpm sync:tests' to regenerate." >&2
  exit 2
fi

exit 0
